# Generated by Django 3.2 on 2021-12-03 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_idea_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='logs',
        ),
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ideas.idea')),
            ],
        ),
    ]
