# Generated by Django 3.2 on 2021-12-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_auto_20211203_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='logs',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
