# Generated by Django 3.2 on 2021-12-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_auto_20211204_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='incubation_certificate',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
