# Generated by Django 3.2 on 2021-12-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0008_idea_incubation_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='incubation_certificate',
        ),
    ]
