# Generated by Django 3.2 on 2021-12-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_remove_idea_incubation_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='actual_technology_completed_and_qualified_through_test_and_demonstration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='actual_technology_qualified_through_successful_mission_operations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='analytical_and_experimental_critical_function_and_or_characteristic_proof_of_concept',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='basic_principles_observed_and_reported',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='technology_basic_validation_in_a_laboratory_environment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='technology_basic_validation_in_a_relevant_environment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='technology_concept_and_or_application_formulated',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='technology_model_or_prototype_demonstration_in_a_relevant_environment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='technology_prototype_demonstration_in_an_operational_environment',
            field=models.TextField(blank=True),
        ),
    ]
